// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlgen

type PaginationInput struct {
	After  *string `json:"after"`
	First  *int    `json:"first"`
	Before *string `json:"before"`
	Last   *int    `json:"last"`
	Skip   *int    `json:"skip"`
}

type UserCreateInput struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}

type UserUpdateInput struct {
	FirstName *string `json:"firstName"`
	LastName  *string `json:"lastName"`
	Email     *string `json:"email"`
}

type UserWhereUniqueInput struct {
	ID    *string `json:"id"`
	Email *string `json:"email"`
}
